---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  namespace: dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      nodeSelector:
        service: dotnet
      tolerations:
        - key: service
          operator: Equal
          value: dotnet
          effect: NoSchedule
      containers:
        - name: dotnet-app
          image: eduyupanqui/dotnet-app:v2
          ports:
            - name: http
              containerPort: 8000
            - name: metrics
              containerPort: 8081
          env:
            - name: GIN_MODE
              value: release
          resources:
            requests:
              memory: 512Mi
              cpu: "2"
            limits:
              memory: 512Mi
              cpu: "3"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: dotnet-app
