@dotnet_app_HostAddress = http://192.168.56.246:8000

###
GET {{dotnet_app_HostAddress}}/api/devices
Accept: application/json

###

GET {{dotnet_app_HostAddress}}/api/images
Accept: application/json