version: '3'

services:
  minio:
    image: minio/minio
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - local-network
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=devops123
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=devops123
      - PGDATA=/data/postgres
    networks:
      - local-network
    volumes:
      - 'postgres_data:/data/postgres'
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - 9090:9090
    networks:
      - local-network
    volumes:
      - ./deploy/local/prometheus.yml:/etc/prometheus/prometheus.yml
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    networks:
      - local-network
networks:
  local-network:
    name: local-network
    driver: bridge
volumes:
  minio_data:
    driver: local
  postgres_data:
    driver: local