@go_app_HostAddress = http://localhost:8000
@go_app_BackAddress = http://localhost:8081

GET {{go_app_HostAddress}}/api/devices
Accept: application/json

###
GET {{go_app_HostAddress}}/api/images
Accept: application/json

###
GET {{go_app_HostAddress}}/health
Accept: application/json

###

GET {{go_app_BackAddress}}/metrics

###

