---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spring-app
  namespace: monitoring
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
      - spring
  selector:
    matchLabels:
      app: spring-app
  podMetricsEndpoints:
    - port: metrics
    - path: /actuator/prometheus
