---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spring-app-client
  namespace: monitoring
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: spring-app-client
  podMetricsEndpoints:
    - port: metrics