@spring_app_HostAddress = http://localhost:8000
@spring_app_BackAddress = http://localhost:8081

GET {{spring_app_HostAddress}}/api/devices
Accept: application/json

###

GET {{spring_app_HostAddress}}/api/images
Accept: application/json

###
GET {{spring_app_BackAddress}}/actuator/health
Accept: application/json

###

GET {{spring_app_BackAddress}}/actuator/prometheus

###

