---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dotnet-app
  namespace: dotnet
data:
  config.yaml: |
    ---
    appPort: 8000
    otlpEndpoint: tempo.monitoring:4317
    s3:
      region: us-west-rack1
      bucket: images
      endpoint: http://minio.minio:9000
      pathStyle: true
      user: console
      secret: console123
    db:
      user: admin
      password: psltest
      host: "postgres.postgres"
      database: mydb
