---
appPort: 8000
s3:
  region: us-west-rack1
  bucket: images
  endpoint: http://localhost:9000
  pathStyle: true
  user: admin
  secret: devops123
db:
  user: myuser
  password: devops123
  host: "localhost"
  database: mydb